### ISSUE TITLE
wonderjs依赖安装及gulp问题

### ISSUE THREAD

**Issue by olakes** [Wonder-Technology/Wonder.js#22]
通过yarn安装依赖失败：（
```
 yarn
yarn install v1.7.0
[1/4] Resolving packages...
warning Resolution field "wonder-commonlib@0.2.23" is incompatible with requested version "wonder-commonlib@0.2.13"
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/4] ⠂ waiting...
[-/4] ⠂ waiting...
[3/4] ⠂ puppeteer
error E:\WonderLab\Wonder.js\node_modules\puppeteer: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: E:\WonderLab\Wonder.js\node_modules\puppeteer
Output:
ERROR: Failed to download **Chromium r555668!** Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: read ECONNRESET
```

yarn install --ignore-scripts似乎可以解决问题，但是运行gulp有奇怪错误。
```
yarn install --ignore-scripts
yarn install v1.7.0
[1/4] Resolving packages...
warning Resolution field "wonder-commonlib@0.2.23" is incompatible with requested version "wonder-commonlib@0.2.13"
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning Ignored scripts due to flag.
Done in 13.43s.
```

运行gullp报错
```
gulp
module.js:538
    throw err;
    ^

Error: Cannot find module **'wonder-log/lib/js/src/Log.js'**


    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\WonderLab\Wonder.js\lib\js\test\e2e\performance\TestPerformance.js:6:21)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

发现node_modules目录下 wonder-log/lib/js目录没有/src/Log.js文件
![截图](https://i.loli.net/2018/07/03/5b3ae9543ba1a.jpg)

**Comment by yyc-git** [comment]
@olakes 谢谢你提的issue哈～

fixed in v1.0.0-alpha.21.1

新版本中，使用"yarn install"可以正常安装。

"npm run buildAll"可编译reason，并用rollup打包wd.js, wd.render.worker.js
"npm run test:watch"可单元测试

如果要进行e2e测试，需要先执行gulp命令，安装puppeteer：
gulp installPuppeteer

render test:
npm run test:render

performance test:
npm run test:pf
